version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Matech123"
      ACCEPT_EULA: "Y"
    ports:
      - "21433:1433"
    restart: unless-stopped
    networks:
      - webnet

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/Apps/CleanArchitecture.Api/Dockerfile
    ports:
      #- "5006:443"
      - "5005:80"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=5006
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=Matech123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cleanarchitecture.pfx
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=sql-server-db;Database=CleanArchitectureDb;User=sa;Password=Matech123;MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
      - "ElasticConfiguration__Uri=http://es01:9200"
    #volumes:
      #- ./https/cleanarchitecture.pfx:/https/cleanarchitecture.pfx:ro
    restart: on-failure
    networks:
      - webnet
    depends_on:
      - sql-server-db
      - es01
   
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: unless-stopped
    networks:
      - webnet

  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    restart: unless-stopped
    networks:
      - webnet

volumes:
  data01:
    driver: local

networks:
  webnet:
    driver: bridge
